# rules-config.yaml
rules-config:
  types:
    typeA:
      - checkTTTypeRule
      - validateCurrencyRule
#      - VerifyCurrencyCutoffTimeRule
#      - VerifySwiftCurrencyRule
#      - VerifyOrAssignReimbursingBankRule
#      - VerifyNostroAgentForTTToMyanmarRule
#      - AssignNostroAgentForSpecialConditionRule
#      - ValidateValueDateRule
#      - ValidateSwiftBICForTag53Rule
#      - CalcPercentageAllocatedForNonGourShaRule
#      - CalcPercentageAllocatedForGourRule
    typeB:
      - checkTTTypeRule
#      - ValidateCurrencyRule
#      - VerifyCurrencyCutoffTimeRule
#      - VerifySwiftCurrencyRule
#      - VerifyOrAssignReimbursingBankRule